
import { GeneratedResult } from '../types';

export const downloadAsTxt = (data: GeneratedResult, context: string) => {
  let content = `PERSPECTO UX REPORT\n`;
  content += `===================\n\n`;
  
  content += `PROJECT CONTEXT\n`;
  content += `${context}\n\n`;
  content += `----------------------------------------\n\n`;

  if (data.persona) {
    const p = data.persona;
    content += `USER PERSONA\n\n`;
    content += `Name: ${p.name}\n`;
    content += `Role: ${p.role}\n\n`;

    content += `GOALS:\n`;
    p.goals.forEach(g => content += `- ${g}\n`);
    content += `\n`;

    content += `NEEDS:\n`;
    p.needs.forEach(n => content += `- ${n}\n`);
    content += `\n`;

    content += `PAINS:\n`;
    p.pains.forEach(pn => content += `- ${pn}\n`);
    content += `\n`;

    content += `KEY TASKS:\n`;
    p.tasks.forEach(t => content += `- ${t}\n`);
    content += `\n`;
    content += `----------------------------------------\n\n`;
  }

  if (data.jtbd && data.jtbd.length > 0) {
    content += `JOBS TO BE DONE (JTBD)\n\n`;
    
    data.jtbd.forEach((item, index) => {
      content += `Job #${index + 1}\n`;
      content += `Situation (When I...): ${item.situation}\n`;
      content += `Motivation (I want to...): ${item.motivation}\n`;
      content += `Outcome (So I can...): ${item.outcome}\n\n`;
    });
  }

  content += `\nGenerated by Perspecto AI\n`;

  // Trigger Download
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `Perspecto-Report-${Date.now()}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const downloadAsPng = (data: GeneratedResult, context: string, filename: string) => {
  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d');
  if (!ctx) return;

  // Setup generic size
  const width = 800;
  // Calculate approximate height based on content
  let estimatedHeight = 400; // Header + Footer
  if (context) estimatedHeight += 100;
  if (data.persona) estimatedHeight += 600;
  if (data.jtbd) estimatedHeight += data.jtbd.length * 150;
  
  const height = Math.max(1200, estimatedHeight);
  const padding = 40;
  const lineHeight = 24;

  canvas.width = width;
  canvas.height = height;

  // Fill Background
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, width, height);

  // Text Config
  ctx.fillStyle = '#111827'; // Gray-900
  ctx.font = 'bold 28px sans-serif';
  let y = padding + 28;

  // Title
  ctx.fillText('Perspecto UX Report', padding, y);
  y += lineHeight * 2;

  // Context
  ctx.fillStyle = '#374151'; // Gray-700
  ctx.font = 'bold 16px sans-serif';
  ctx.fillText('PROJECT CONTEXT', padding, y);
  y += lineHeight;
  
  ctx.font = '14px sans-serif';
  ctx.fillStyle = '#4B5563'; // Gray-600
  
  const wrapText = (text: string, x: number, y: number, maxWidth: number, lineHeight: number) => {
    const words = text.split(' ');
    let line = '';
    let currentY = y;

    for (let n = 0; n < words.length; n++) {
      const testLine = line + words[n] + ' ';
      const metrics = ctx.measureText(testLine);
      const testWidth = metrics.width;
      if (testWidth > maxWidth && n > 0) {
        ctx.fillText(line, x, currentY);
        line = words[n] + ' ';
        currentY += lineHeight;
      } else {
        line = testLine;
      }
    }
    ctx.fillText(line, x, currentY);
    return currentY + lineHeight;
  };

  y = wrapText(context, padding, y, width - (padding * 2), 20);
  y += lineHeight * 1.5;

  // Separator
  ctx.beginPath();
  ctx.moveTo(padding, y);
  ctx.lineTo(width - padding, y);
  ctx.strokeStyle = '#E5E7EB'; // Gray-200
  ctx.lineWidth = 2;
  ctx.stroke();
  y += lineHeight * 2;

  if (data.persona) {
    ctx.fillStyle = '#111827';
    ctx.font = 'bold 22px sans-serif';
    ctx.fillText('User Persona', padding, y);
    y += lineHeight * 1.5;

    // Header Box
    ctx.fillStyle = '#F3F4F6'; // Gray-100
    ctx.fillRect(padding, y, width - (padding * 2), 80);
    
    ctx.fillStyle = '#111827';
    ctx.font = 'bold 20px sans-serif';
    ctx.fillText(data.persona.name, padding + 20, y + 35);
    
    ctx.fillStyle = '#7C3AED'; // Primary-600 ish
    ctx.font = '16px sans-serif';
    ctx.fillText(data.persona.role, padding + 20, y + 60);
    
    y += 100;

    const sections = [
        { title: 'GOALS', items: data.persona.goals },
        { title: 'NEEDS', items: data.persona.needs },
        { title: 'PAINS', items: data.persona.pains }
    ];

    sections.forEach(section => {
        ctx.fillStyle = '#374151';
        ctx.font = 'bold 14px sans-serif';
        ctx.fillText(section.title, padding, y);
        y += lineHeight;
        
        ctx.font = '14px sans-serif';
        ctx.fillStyle = '#4B5563';
        section.items.forEach(item => {
            ctx.fillText(`• ${item}`, padding + 10, y);
            y += lineHeight;
        });
        y += lineHeight * 0.5;
    });
    
    y += lineHeight;
  }

  if (data.jtbd && data.jtbd.length > 0) {
    // Separator if persona exists
    if (data.persona) {
        ctx.beginPath();
        ctx.moveTo(padding, y);
        ctx.lineTo(width - padding, y);
        ctx.strokeStyle = '#E5E7EB';
        ctx.stroke();
        y += lineHeight * 2;
    }
    
    ctx.fillStyle = '#111827';
    ctx.font = 'bold 22px sans-serif';
    ctx.fillText('Jobs-To-Be-Done', padding, y);
    y += lineHeight * 1.5;

    data.jtbd.forEach((job, idx) => {
        // Card bg
        const startY = y;
        
        ctx.fillStyle = '#111827';
        ctx.font = 'bold 16px sans-serif';
        ctx.fillText(`Job #${idx + 1}`, padding, y + 20);
        y += lineHeight * 1.5;
        
        ctx.font = 'bold 14px sans-serif';
        ctx.fillStyle = '#4B5563';
        
        y = wrapText(`When I: ${job.situation}`, padding, y, width - padding*2, 20);
        y += 8;
        y = wrapText(`I want to: ${job.motivation}`, padding, y, width - padding*2, 20);
        y += 8;
        y = wrapText(`So I can: ${job.outcome}`, padding, y, width - padding*2, 20);
        y += lineHeight * 1.5;
        
        // Box outline
        ctx.strokeStyle = '#E5E7EB';
        ctx.lineWidth = 1;
        ctx.strokeRect(padding - 10, startY, width - (padding * 2) + 20, y - startY - 10);
    });
  }

  // Footer
  ctx.fillStyle = '#9CA3AF'; // Gray-400
  ctx.font = 'italic 12px sans-serif';
  ctx.fillText('Generated by Perspecto AI', padding, height - 20);

  // Download
  const link = document.createElement('a');
  link.download = `${filename}.png`;
  link.href = canvas.toDataURL('image/png');
  link.click();
};
